import { Stack } from '@chakra-ui/react'
import Head from 'next/head'
import Container from '../components/cardsContainer/Container'
import Header from '../components/header/Header'


export default function Home() {
  return (
    <Stack minH='100vh' bgImage='/bg-bottom.svg' bgRepeat='no-repeat' bgPosition='bottom left'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack w='100vw' bgImage='/bg-top.svg' bgRepeat='no-repeat' bgPosition='top right'>
        <Header />
        <Container />
      </Stack>
    </Stack>
  )
}
